language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eapriala/Learning_docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true eapriala/Learning_docker-react npm run test -- --coverage